"""create time off records table

Revision ID: 127077450812
Revises: 80ac81d559d8
Create Date: 2026-08-15 21:06:14.116683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127077450812'
down_revision: Union[str, Sequence[str], None] = '80ac81d559d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_off_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('leave_type', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_off_records_agent_id'), 'time_off_records', ['agent_id'], unique=False)
    op.create_index(op.f('ix_time_off_records_created_by_admin_id'), 'time_off_records', ['created_by_admin_id'], unique=False)
    op.create_index(op.f('ix_time_off_records_id'), 'time_off_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_off_records_id'), table_name='time_off_records')
    op.drop_index(op.f('ix_time_off_records_created_by_admin_id'), table_name='time_off_records')
    op.drop_index(op.f('ix_time_off_records_agent_id'), table_name='time_off_records')
    op.drop_table('time_off_records')
    # ### end Alembic commands ###
