"""create attendance records table

Revision ID: 4fb89dae1c3c
Revises: 342ebdf855e5
Create Date: 2026-08-15 01:52:46.167605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fb89dae1c3c'
down_revision: Union[str, Sequence[str], None] = '342ebdf855e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_agent_id'), 'attendance_records', ['agent_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_created_by_admin_id'), 'attendance_records', ['created_by_admin_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_created_by_admin_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_agent_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    # ### end Alembic commands ###
