"""create reports and attachments tables

Revision ID: 65c392b636b9
Revises: 127077450812
Create Date: 2026-08-15 21:49:44.470168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c392b636b9'
down_revision: Union[str, Sequence[str], None] = '127077450812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_records_agent_id'), 'report_records', ['agent_id'], unique=False)
    op.create_index(op.f('ix_report_records_created_by_admin_id'), 'report_records', ['created_by_admin_id'], unique=False)
    op.create_index(op.f('ix_report_records_id'), 'report_records', ['id'], unique=False)
    op.create_table('report_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_report_attachments_id'), 'report_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_report_attachments_report_id'), 'report_attachments', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_attachments_report_id'), table_name='report_attachments')
    op.drop_index(op.f('ix_report_attachments_id'), table_name='report_attachments')
    op.drop_table('report_attachments')
    op.drop_index(op.f('ix_report_records_id'), table_name='report_records')
    op.drop_index(op.f('ix_report_records_created_by_admin_id'), table_name='report_records')
    op.drop_index(op.f('ix_report_records_agent_id'), table_name='report_records')
    op.drop_table('report_records')
    # ### end Alembic commands ###
