"""create follow up records table

Revision ID: 80ac81d559d8
Revises: 4fb89dae1c3c
Create Date: 2026-08-15 20:26:38.607833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ac81d559d8'
down_revision: Union[str, Sequence[str], None] = '4fb89dae1c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_up_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_up_records_agent_id'), 'follow_up_records', ['agent_id'], unique=False)
    op.create_index(op.f('ix_follow_up_records_created_by_admin_id'), 'follow_up_records', ['created_by_admin_id'], unique=False)
    op.create_index(op.f('ix_follow_up_records_id'), 'follow_up_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follow_up_records_id'), table_name='follow_up_records')
    op.drop_index(op.f('ix_follow_up_records_created_by_admin_id'), table_name='follow_up_records')
    op.drop_index(op.f('ix_follow_up_records_agent_id'), table_name='follow_up_records')
    op.drop_table('follow_up_records')
    # ### end Alembic commands ###
