"""add agent access code hash

Revision ID: af7b83b902a1
Revises: 390a6c69a16e
Create Date: 2026-08-14 23:12:12.861932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7b83b902a1'
down_revision: Union[str, Sequence[str], None] = '390a6c69a16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('access_code_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'access_code_hash')
    # ### end Alembic commands ###
